trigger:
- main  # Adjust to your branch name if it's not 'main'

pool:
  name: 'AnsibleAgent'  # Use your self-hosted agent pool name

steps:
- script: |
    echo "hello world" >> /home/ansible_user/file1.txt
  displayName: "Echo hello world into file1.txt"
